#ifndef METHODS_H
#define METHODS_H
enum IntConstantIDs{IMG_RES_X=0, IMG_RES_Y, COLS, ROWS, GRID_SIZE, INT_CONSTANTS_COUNT};
enum FloatConstantIDs{SCAN_RANGE_START_1=0, SCAN_RANGE_START_2, SCAN_RANGE_START_3, SCAN_RANGE_START_4, SCAN_RANGE_STEP_1, SCAN_RANGE_STEP_2, SCAN_RANGE_STEP_3, SCAN_RANGE_STEP_4, PX_SIZE_X_HALF, PX_SIZE_Y_HALF, FLOAT_CONSTANTS_COUNT};
constexpr int BLOCK_OFFSET_COUNT{5};
enum DataPointersIDs{SURFACES, TEXTURES, POINTERS_COUNT};
enum FileNames {RENDER_IMAGE, OUTPUT_COUNT};
constexpr int CHANNEL_COUNT{3};
constexpr int FOCUS_STEPS_COUNT{16};
#endif
